[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true
  conditions = { Role = ["admin"] }

[[redirects]]
  from = "/admin"
  to = "/login"
  status = 302
  force = true

[[redirects]]
  from = "/admin/"
  to = "/admin/index.html"
  status = 200
  force = true
  conditions = { Role = ["admin"] }

[[redirects]]
  from = "/admin/"
  to = "/login"
  status = 302
  force = true
